#!/bin/bash
#
# Shell Script para executar o programa JAVA do programa "k-conexo"

if [ $# -ne 1 ]
then
	echo "Erro. Modo de uso: ./k-conexo <arquivo>";
	exit 1
fi

# executa a classe isomorfos, definido o classpath (-cp) como ./bin
java -cp bin KConexo $1
